# Chapter 3 - It Starts with a Tensor

## Part II: Named Tensors

In [1]:
import torch

In [4]:
_ = torch.tensor([0.2126, 0.7152, 0.0722])
_

tensor([0.2126, 0.7152, 0.0722])

In [5]:
img_t = torch.rand(3, 5, 5) # shape: [channels, rows, columns]
img_t

tensor([[[0.0751, 0.3602, 0.1868, 0.6420, 0.9561],
         [0.6469, 0.3584, 0.3482, 0.2537, 0.9192],
         [0.9265, 0.8068, 0.6904, 0.2248, 0.3307],
         [0.3127, 0.0189, 0.5042, 0.7750, 0.8853],
         [0.9639, 0.0698, 0.5397, 0.7294, 0.4256]],

        [[0.7042, 0.2465, 0.7763, 0.7548, 0.5532],
         [0.0387, 0.7107, 0.2033, 0.1189, 0.2922],
         [0.3317, 0.2222, 0.4381, 0.4629, 0.5940],
         [0.7532, 0.2444, 0.4431, 0.4905, 0.7584],
         [0.2473, 0.8261, 0.7704, 0.7333, 0.2259]],

        [[0.3878, 0.4787, 0.0083, 0.7802, 0.6803],
         [0.5864, 0.5983, 0.3736, 0.8486, 0.6060],
         [0.0129, 0.5737, 0.3061, 0.2584, 0.1265],
         [0.8278, 0.3856, 0.0999, 0.9498, 0.8361],
         [0.5053, 0.7760, 0.0059, 0.4687, 0.8886]]])

In [7]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [8]:
batch_t = torch.rand(2, 3, 5, 5) # shape: [batch, channels, rows, columns]
batch_t

tensor([[[[0.1912, 0.5573, 0.2705, 0.5347, 0.2379],
          [0.3625, 0.3127, 0.7207, 0.8050, 0.0974],
          [0.2794, 0.1514, 0.9426, 0.0345, 0.4845],
          [0.7548, 0.3143, 0.7165, 0.0757, 0.9597],
          [0.0554, 0.2309, 0.6679, 0.5269, 0.8012]],

         [[0.1139, 0.8542, 0.3098, 0.6938, 0.3869],
          [0.9905, 0.9407, 0.0259, 0.6903, 0.6793],
          [0.1613, 0.1218, 0.9189, 0.7288, 0.6209],
          [0.1847, 0.5874, 0.6765, 0.2666, 0.9625],
          [0.5177, 0.9573, 0.8658, 0.5807, 0.3460]],

         [[0.6843, 0.7910, 0.6201, 0.9391, 0.5831],
          [0.0903, 0.4473, 0.2612, 0.6755, 0.1725],
          [0.9037, 0.1596, 0.3024, 0.6801, 0.0155],
          [0.5923, 0.7027, 0.9166, 0.5670, 0.2063],
          [0.9644, 0.9811, 0.9167, 0.9739, 0.6123]]],


        [[[0.9967, 0.5940, 0.7456, 0.8529, 0.2471],
          [0.4610, 0.8317, 0.5630, 0.7013, 0.1304],
          [0.5033, 0.5742, 0.3019, 0.7553, 0.0072],
          [0.8199, 0.5402, 0.4308, 0.4350, 0.8786],
    

In [9]:
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[0.3890, 0.3618, 0.3238, 0.7256, 0.7298],
        [0.4240, 0.5558, 0.3084, 0.4070, 0.6058],
        [0.4237, 0.5342, 0.4782, 0.3154, 0.3504],
        [0.6312, 0.2163, 0.3491, 0.7384, 0.8266],
        [0.5722, 0.5573, 0.4387, 0.6438, 0.5134]])

In [12]:
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive

tensor([[[0.3298, 0.7342, 0.4001, 0.7225, 0.4027],
         [0.4811, 0.5669, 0.3359, 0.7236, 0.3164],
         [0.4481, 0.1442, 0.7213, 0.4811, 0.3736],
         [0.5106, 0.5348, 0.7699, 0.3031, 0.7095],
         [0.5125, 0.7231, 0.8168, 0.6938, 0.5865]],

        [[0.7784, 0.6409, 0.6265, 0.7997, 0.1954],
         [0.2902, 0.6501, 0.6028, 0.2989, 0.4282],
         [0.6802, 0.7347, 0.4929, 0.6751, 0.2570],
         [0.7816, 0.6752, 0.3845, 0.3763, 0.7476],
         [0.5106, 0.4661, 0.4860, 0.7432, 0.8428]]])

In [13]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [14]:
unsqueezed_weights = weights.unsqueeze(-1)
unsqueezed_weights

tensor([[0.2126],
        [0.7152],
        [0.0722]])

In [17]:
unsqueezed_weights = unsqueezed_weights.unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [18]:
img_weights = (img_t * unsqueezed_weights)
img_weights

tensor([[[1.5959e-02, 7.6578e-02, 3.9721e-02, 1.3650e-01, 2.0326e-01],
         [1.3752e-01, 7.6204e-02, 7.4028e-02, 5.3934e-02, 1.9542e-01],
         [1.9697e-01, 1.7152e-01, 1.4677e-01, 4.7797e-02, 7.0315e-02],
         [6.6476e-02, 4.0155e-03, 1.0720e-01, 1.6477e-01, 1.8822e-01],
         [2.0493e-01, 1.4832e-02, 1.1473e-01, 1.5508e-01, 9.0486e-02]],

        [[5.0367e-01, 1.7633e-01, 5.5519e-01, 5.3980e-01, 3.9562e-01],
         [2.7667e-02, 5.0827e-01, 1.4542e-01, 8.5007e-02, 2.0895e-01],
         [2.3726e-01, 1.5893e-01, 3.1333e-01, 3.3110e-01, 4.2481e-01],
         [5.3870e-01, 1.7483e-01, 3.1690e-01, 3.5080e-01, 5.4244e-01],
         [1.7690e-01, 5.9081e-01, 5.5100e-01, 5.2443e-01, 1.6154e-01]],

        [[2.8001e-02, 3.4564e-02, 5.9856e-04, 5.6327e-02, 4.9114e-02],
         [4.2335e-02, 4.3199e-02, 2.6975e-02, 6.1267e-02, 4.3750e-02],
         [9.3337e-04, 4.1419e-02, 2.2101e-02, 1.8659e-02, 9.1317e-03],
         [5.9767e-02, 2.7843e-02, 7.2099e-03, 6.8575e-02, 6.0368e-02],
  

In [19]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights

tensor([[[[0.0406, 0.1185, 0.0575, 0.1137, 0.0506],
          [0.0771, 0.0665, 0.1532, 0.1712, 0.0207],
          [0.0594, 0.0322, 0.2004, 0.0073, 0.1030],
          [0.1605, 0.0668, 0.1523, 0.0161, 0.2040],
          [0.0118, 0.0491, 0.1420, 0.1120, 0.1703]],

         [[0.0815, 0.6109, 0.2216, 0.4962, 0.2767],
          [0.7084, 0.6728, 0.0185, 0.4937, 0.4858],
          [0.1154, 0.0871, 0.6572, 0.5212, 0.4441],
          [0.1321, 0.4201, 0.4838, 0.1906, 0.6884],
          [0.3703, 0.6846, 0.6192, 0.4153, 0.2475]],

         [[0.0494, 0.0571, 0.0448, 0.0678, 0.0421],
          [0.0065, 0.0323, 0.0189, 0.0488, 0.0125],
          [0.0652, 0.0115, 0.0218, 0.0491, 0.0011],
          [0.0428, 0.0507, 0.0662, 0.0409, 0.0149],
          [0.0696, 0.0708, 0.0662, 0.0703, 0.0442]]],


        [[[0.2119, 0.1263, 0.1585, 0.1813, 0.0525],
          [0.0980, 0.1768, 0.1197, 0.1491, 0.0277],
          [0.1070, 0.1221, 0.0642, 0.1606, 0.0015],
          [0.1743, 0.1148, 0.0916, 0.0925, 0.1868],
    

In [20]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted

tensor([[0.5476, 0.2875, 0.5955, 0.7326, 0.6480],
        [0.2075, 0.6277, 0.2464, 0.2002, 0.4481],
        [0.4352, 0.3719, 0.4822, 0.3976, 0.5043],
        [0.6649, 0.2067, 0.4313, 0.5842, 0.7910],
        [0.4183, 0.6617, 0.6662, 0.7134, 0.3162]])

In [21]:
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted

tensor([[[0.1715, 0.7865, 0.3238, 0.6776, 0.3694],
         [0.7920, 0.7716, 0.1906, 0.7136, 0.5190],
         [0.2400, 0.1308, 0.8794, 0.5777, 0.5482],
         [0.3353, 0.5376, 0.7023, 0.2477, 0.9073],
         [0.4517, 0.8045, 0.8274, 0.5977, 0.4620]],

        [[0.7525, 0.4917, 0.4572, 0.7720, 0.1985],
         [0.3531, 0.8440, 0.6253, 0.2581, 0.7175],
         [0.5981, 0.8644, 0.7166, 0.6994, 0.2672],
         [0.8925, 0.5835, 0.5162, 0.1883, 0.8819],
         [0.5816, 0.4150, 0.2129, 0.5819, 0.7814]]])

In [22]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [25]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722])
weights_named

tensor([0.2126, 0.7152, 0.0722])