# Chapter 3 - It Starts with a Tensor

## Part I: Tensors

In [1]:
a = [1.0, 2.0, 3.0]
a[0]

1.0

In [2]:
a[2] = 4
a

[1.0, 2.0, 4]

In [3]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6) # <1>

points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

2D Tensor:

In [11]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [17]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [18]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [19]:
points[1:, 0]

tensor([5., 2.])

In [20]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [21]:
points.storage

<function Tensor.storage>

In [22]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [23]:
points_storage = points.storage()
points_storage[0]

4.0

In [25]:
points.storage()[1]

1.0

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [28]:
second_point

tensor([5., 3.])

In [29]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
points.stride()

(2, 1)

In [31]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [32]:
second_point.storage_offset()

2

In [33]:
second_point

tensor([5., 3.])

In [34]:
second_point.stride

<function Tensor.stride>

In [35]:
second_point.stride()

(1,)

In [36]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [37]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [38]:
id(points.storage()) == id(points_t.storage())

True

In [39]:
points.stride()

(2, 1)

In [40]:
points_t.stride()

(1, 2)

In [41]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [42]:
some_t.stride()

(20, 5, 1)

In [43]:
transpose_t.stride()

(1, 5, 20)

In [44]:
points.is_contiguous()

True

In [45]:
points_t.is_contiguous()

False

In [46]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [47]:
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [48]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [49]:
double_points = torch.zeros(10, 2).double()
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [50]:
points_64 = torch.rand(5, dtype=torch.double)
points_64

tensor([0.5927, 0.5222, 0.3852, 0.3017, 0.0726], dtype=torch.float64)

In [51]:
points_short = points_64.to(torch.short)
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [52]:
# Reset points back to original value
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

In [53]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [54]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [55]:
some_list[1:4:2]

[1, 3]

In [56]:
points = torch.ones(3, 4)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [58]:
points = torch.from_numpy(points_np)

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0],
                           [5.0, 3.0],
                           [2.0, 1.0]], device='cuda')

In [60]:
a = torch.ones(3, 2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [61]:
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [62]:
a_t2 = torch.transpose(a, 1, 0)
a_t2

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [64]:
a_t3 = torch.transpose(a, 1, 1)
a_t3

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [65]:
b = torch.tensor([[4.0, 1.0],
                  [5.0, 3.0],
                  [2.0, 1.0]])

In [66]:
b

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [67]:
b_t1 = b.T
b_t1

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [70]:
b_t2 = torch.transpose(b, 0, 1)
b_t2

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [71]:
b_t3 = torch.transpose(b, 1, 0)
b_t3

tensor([[4., 5., 2.],
        [1., 3., 1.]])