# Chapter 5 - The Mechanics of Learning

## Part II: Autograd

In [1]:
%matplotlib inline
import numpy as np
import torch
torch.set_printoptions(edgeitems=2)

In [3]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0,
                    3.0, -4.0, 6.0, 13.0, 21.0])

t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])

t_un = 0.1 * t_u

In [4]:
def model(t_u, w, b):
    return w * t_u + b

In [5]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [14]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
params

tensor([1., 0.], requires_grad=True)

In [15]:
params.grad is None

True

In [16]:
loss = loss_fn(model(t_u, *params), t_c)
loss.backward()

params.grad

tensor([4517.2969,   82.6000])

In [17]:
if params.grad is not None:
    params.grad.zero_()

In [18]:
def training_loop(n_epochs, lr, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        if params.grad is not None:
            params.grad.zero_()
            
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)
        loss.backward()
        
        with torch.no_grad():
            params -= lr * params.grad
        
        if epoch % 500 == 0:
            print('Epoch: {}, Loss: {}'.format(epoch, float(loss)))
    
    return params

In [19]:
training_loop(
    n_epochs=5000,
    lr=1e-2,
    params=torch.tensor([1.0, 0.0], requires_grad=True),
    t_u=t_un,
    t_c=t_c)

Epoch: 500, Loss: 7.8601155281066895
Epoch: 1000, Loss: 3.828537940979004
Epoch: 1500, Loss: 3.092191219329834
Epoch: 2000, Loss: 2.9576973915100098
Epoch: 2500, Loss: 2.933133840560913
Epoch: 3000, Loss: 2.9286482334136963
Epoch: 3500, Loss: 2.9278297424316406
Epoch: 4000, Loss: 2.9276793003082275
Epoch: 4500, Loss: 2.92765212059021
Epoch: 5000, Loss: 2.9276468753814697


tensor([  5.3671, -17.3012], requires_grad=True)